### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by therawk** [SyncfusionExamples/ej2-custom-styles#1]
I wanted to generate custom css for the Vol 2 release from yesterday.
This is the error I'm getting:

 Select Essential JS 2 Packages for Custom Styles @syncfusion/ej2-buttons, @syncfusion/ej2-calendars, @syncfusion/ej2-c
ards, @syncfusion/ej2-charts, @syncfusion/ej2-circulargauge, @syncfusion/ej2-dropdowns, @syncfusion/ej2-grids, @syncfusi
on/ej2-inputs, @syncfusion/ej2-lineargauge, @syncfusion/ej2-lists, @syncfusion/ej2-maps, @syncfusion/ej2-navigations, @s
yncfusion/ej2-popups, @syncfusion/ej2-schedule, @syncfusion/ej2-splitbuttons
(node:26040) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'length' of undefined
    at getDependencies (C:\ej2-custom-styles\gulpfile.js:155:38)
    at createComponentStyles (C:\ej2-custom-styles\gulpfile.js:146:26)
    at inquirer.prompt.then.answer (C:\ej2-custom-styles\gulpfile.js:88:21)
    at <anonymous>
(node:26040) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:26040) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by ajithr** [comment]
Hi @therawk ,

Thanks for your interest in Essential JS 2.

We are glad to let you know that, the ThemeStudio for Essential JS 2 components has been rolled out in Volume 2, 2018 release. So we suggest you to use the below web tool to generate custom styles instead of generating from this `ej2-custom-styles` temporary plugin.

https://ej2.syncfusion.com/themestudio/

Regards,
Ajith R
